import { $t } from '../i18n/index'
import { winIdFromIana } from './winIanaMap'

// 每个时区的定义（IANA id + 固定 offset + 翻译 key）
// 顺序从 UTC-12 到 UTC+14，基本保持与 Windows 时区列表一致
const ZONES: Array<{ offset: string; iana: string; labelKey: string; winId?: string }> = [
  { offset: '(UTC-12:00)', iana: 'Etc/GMT+12', labelKey: 'timeZone.Etc/GMT+12' },
  { offset: '(UTC-11:00)', iana: 'Etc/GMT+11', labelKey: 'timeZone.Etc/GMT+11' },
  { offset: '(UTC-10:00)', iana: 'America/Adak', labelKey: 'timeZone.America/Adak' },
  { offset: '(UTC-10:00)', iana: 'Pacific/Honolulu', labelKey: 'timeZone.Pacific/Honolulu' },
  { offset: '(UTC-09:30)', iana: 'Pacific/Marquesas', labelKey: 'timeZone.Pacific/Marquesas' },
  { offset: '(UTC-09:00)', iana: 'America/Anchorage', labelKey: 'timeZone.America/Anchorage' },
  { offset: '(UTC-09:00)', iana: 'Etc/GMT+9', labelKey: 'timeZone.Etc/GMT+9' },
  { offset: '(UTC-08:00)', iana: 'America/Los_Angeles', labelKey: 'timeZone.America/Los_Angeles' },
  { offset: '(UTC-08:00)', iana: 'America/Tijuana', labelKey: 'timeZone.America/Tijuana' },
  { offset: '(UTC-08:00)', iana: 'Etc/GMT+8', labelKey: 'timeZone.Etc/GMT+8' },
  { offset: '(UTC-07:00)', iana: 'America/Mazatlan', labelKey: 'timeZone.America/Mazatlan' },
  { offset: '(UTC-07:00)', iana: 'America/Denver', labelKey: 'timeZone.America/Denver' },
  { offset: '(UTC-07:00)', iana: 'America/Phoenix', labelKey: 'timeZone.America/Phoenix' },
  { offset: '(UTC-07:00)', iana: 'America/Whitehorse', labelKey: 'timeZone.America/Whitehorse' },
  { offset: '(UTC-06:00)', iana: 'Pacific/Easter', labelKey: 'timeZone.Pacific/Easter' },
  { offset: '(UTC-06:00)', iana: 'America/Mexico_City', labelKey: 'timeZone.America/Mexico_City' },
  { offset: '(UTC-06:00)', iana: 'America/Regina', labelKey: 'timeZone.America/Regina' },
  { offset: '(UTC-06:00)', iana: 'America/Chicago', labelKey: 'timeZone.America/Chicago' },
  { offset: '(UTC-06:00)', iana: 'America/Guatemala', labelKey: 'timeZone.America/Guatemala' },
  { offset: '(UTC-05:00)', iana: 'America/Bogota', labelKey: 'timeZone.America/Bogota' },
  { offset: '(UTC-05:00)', iana: 'America/New_York', labelKey: 'timeZone.America/New_York' },
  { offset: '(UTC-05:00)', iana: 'America/Havana', labelKey: 'timeZone.America/Havana' },
  { offset: '(UTC-05:00)', iana: 'America/Port-au-Prince', labelKey: 'timeZone.America/Port-au-Prince' },
  { offset: '(UTC-05:00)', iana: 'America/Cancun', labelKey: 'timeZone.America/Cancun' },
  { offset: '(UTC-05:00)', iana: 'America/Grand_Turk', labelKey: 'timeZone.America/Grand_Turk' },
  { offset: '(UTC-05:00)', iana: 'America/Indiana/Indianapolis', labelKey: 'timeZone.America/Indiana/Indianapolis' },
  { offset: '(UTC-04:00)', iana: 'America/Halifax', labelKey: 'timeZone.America/Halifax' },
  { offset: '(UTC-04:00)', iana: 'America/Caracas', labelKey: 'timeZone.America/Caracas' },
  { offset: '(UTC-04:00)', iana: 'America/Cuiaba', labelKey: 'timeZone.America/Cuiaba' },
  { offset: '(UTC-04:00)', iana: 'America/Port_of_Spain', labelKey: 'timeZone.America/Port_of_Spain' },
  { offset: '(UTC-04:00)', iana: 'America/Santiago', labelKey: 'timeZone.America/Santiago' },
  { offset: '(UTC-04:00)', iana: 'America/Asuncion', labelKey: 'timeZone.America/Asuncion' },
  { offset: '(UTC-03:30)', iana: 'America/St_Johns', labelKey: 'timeZone.America/St_Johns' },
  { offset: '(UTC-03:00)', iana: 'America/Araguaina', labelKey: 'timeZone.America/Araguaina' },
  { offset: '(UTC-03:00)', iana: 'America/Sao_Paulo', labelKey: 'timeZone.America/Sao_Paulo' },
  { offset: '(UTC-03:00)', iana: 'America/Argentina/Buenos_Aires', labelKey: 'timeZone.America/Argentina/Buenos_Aires' },
  { offset: '(UTC-03:00)', iana: 'America/Cayenne', labelKey: 'timeZone.America/Cayenne' },
  { offset: '(UTC-03:00)', iana: 'America/Montevideo', labelKey: 'timeZone.America/Montevideo' },
  { offset: '(UTC-03:00)', iana: 'America/Punta_Arenas', labelKey: 'timeZone.America/Punta_Arenas' },
  { offset: '(UTC-03:00)', iana: 'America/El_Salvador', labelKey: 'timeZone.America/El_Salvador' },
  { offset: '(UTC-03:00)', iana: 'America/Miquelon', labelKey: 'timeZone.America/Miquelon' },
  { offset: '(UTC-02:00)', iana: 'America/Nuuk', labelKey: 'timeZone.America/Nuuk' },
  { offset: '(UTC-02:00)', iana: 'Etc/GMT+2', labelKey: 'timeZone.Etc/GMT+2' },
  { offset: '(UTC-01:00)', iana: 'Atlantic/Cape_Verde', labelKey: 'timeZone.Atlantic/Cape_Verde' },
  { offset: '(UTC-01:00)', iana: 'Atlantic/Azores', labelKey: 'timeZone.Atlantic/Azores' },
  { offset: '(UTC)',       iana: 'Etc/GMT',        labelKey: 'timeZone.Etc/GMT' },
  { offset: '(UTC+00:00)', iana: 'Europe/London', labelKey: 'timeZone.Europe/London' },
  { offset: '(UTC+00:00)', iana: 'Africa/Monrovia', labelKey: 'timeZone.Africa/Monrovia' },
  { offset: '(UTC+00:00)', iana: 'Africa/Sao_Tome', labelKey: 'timeZone.Africa/Sao_Tome' },
  { offset: '(UTC+01:00)', iana: 'Africa/Casablanca', labelKey: 'timeZone.Africa/Casablanca' },
  { offset: '(UTC+01:00)', iana: 'Europe/Berlin', labelKey: 'timeZone.Europe/Berlin' },
  { offset: '(UTC+01:00)', iana: 'Europe/Belgrade', labelKey: 'timeZone.Europe/Belgrade' },
  { offset: '(UTC+01:00)', iana: 'Europe/Paris', labelKey: 'timeZone.Europe/Paris' },
  { offset: '(UTC+01:00)', iana: 'Europe/Sarajevo', labelKey: 'timeZone.Europe/Sarajevo' },
  { offset: '(UTC+01:00)', iana: 'Africa/Lagos', labelKey: 'timeZone.Africa/Lagos' },
  { offset: '(UTC+02:00)', iana: 'Asia/Beirut', labelKey: 'timeZone.Asia/Beirut' },
  { offset: '(UTC+02:00)', iana: 'Africa/Tripoli', labelKey: 'timeZone.Africa/Tripoli' },
  { offset: '(UTC+02:00)', iana: 'Africa/Johannesburg', labelKey: 'timeZone.Africa/Johannesburg' },
  { offset: '(UTC+02:00)', iana: 'Europe/Helsinki', labelKey: 'timeZone.Europe/Helsinki' },
  { offset: '(UTC+02:00)', iana: 'Europe/Chisinau', labelKey: 'timeZone.Europe/Chisinau' },
  { offset: '(UTC+02:00)', iana: 'Europe/Kaliningrad', labelKey: 'timeZone.Europe/Kaliningrad' },
  { offset: '(UTC+02:00)', iana: 'Asia/Gaza', labelKey: 'timeZone.Asia/Gaza' },
  { offset: '(UTC+02:00)', iana: 'Africa/Khartoum', labelKey: 'timeZone.Africa/Khartoum' },
  { offset: '(UTC+02:00)', iana: 'Africa/Cairo', labelKey: 'timeZone.Africa/Cairo' },
  { offset: '(UTC+02:00)', iana: 'Africa/Windhoek', labelKey: 'timeZone.Africa/Windhoek' },
  { offset: '(UTC+02:00)', iana: 'Europe/Athens', labelKey: 'timeZone.Europe/Athens' },
  { offset: '(UTC+02:00)', iana: 'Asia/Jerusalem', labelKey: 'timeZone.Asia/Jerusalem' },
  { offset: '(UTC+02:00)', iana: 'Africa/Juba', labelKey: 'timeZone.Africa/Juba' },
  { offset: '(UTC+03:00)', iana: 'Asia/Amman', labelKey: 'timeZone.Asia/Amman' },
  { offset: '(UTC+03:00)', iana: 'Asia/Baghdad', labelKey: 'timeZone.Asia/Baghdad' },
  { offset: '(UTC+03:00)', iana: 'Asia/Damascus', labelKey: 'timeZone.Asia/Damascus' },
  { offset: '(UTC+03:00)', iana: 'Europe/Volgograd', labelKey: 'timeZone.Europe/Volgograd' },
  { offset: '(UTC+03:00)', iana: 'Asia/Kuwait', labelKey: 'timeZone.Asia/Kuwait' },
  { offset: '(UTC+03:00)', iana: 'Europe/Minsk', labelKey: 'timeZone.Europe/Minsk' },
  { offset: '(UTC+03:00)', iana: 'Europe/Moscow', labelKey: 'timeZone.Europe/Moscow' },
  { offset: '(UTC+03:00)', iana: 'Africa/Nairobi', labelKey: 'timeZone.Africa/Nairobi' },
  { offset: '(UTC+03:00)', iana: 'Europe/Istanbul', labelKey: 'timeZone.Europe/Istanbul' },
  { offset: '(UTC+03:30)', iana: 'Asia/Tehran', labelKey: 'timeZone.Asia/Tehran' },
  { offset: '(UTC+04:00)', iana: 'Asia/Dubai', labelKey: 'timeZone.Asia/Dubai' },
  { offset: '(UTC+04:00)', iana: 'Europe/Astrakhan', labelKey: 'timeZone.Europe/Astrakhan' },
  { offset: '(UTC+04:00)', iana: 'Asia/Yerevan', labelKey: 'timeZone.Asia/Yerevan' },
  { offset: '(UTC+04:00)', iana: 'Asia/Baku', labelKey: 'timeZone.Asia/Baku' },
  { offset: '(UTC+04:00)', iana: 'Asia/Tbilisi', labelKey: 'timeZone.Asia/Tbilisi' },
  { offset: '(UTC+04:00)', iana: 'Indian/Mauritius', labelKey: 'timeZone.Indian/Mauritius' },
  { offset: '(UTC+04:00)', iana: 'Europe/Saratov', labelKey: 'timeZone.Europe/Saratov' },
  { offset: '(UTC+04:00)', iana: 'Europe/Ulyanovsk', labelKey: 'timeZone.Europe/Ulyanovsk' },
  { offset: '(UTC+04:30)', iana: 'Asia/Kabul', labelKey: 'timeZone.Asia/Kabul' },
  { offset: '(UTC+05:00)', iana: 'Asia/Ashgabat', labelKey: 'timeZone.Asia/Ashgabat' },
  { offset: '(UTC+05:00)', iana: 'Asia/Almaty', labelKey: 'timeZone.Asia/Almaty' },
  { offset: '(UTC+05:00)', iana: 'Asia/Yekaterinburg', labelKey: 'timeZone.Asia/Yekaterinburg' },
  { offset: '(UTC+05:00)', iana: 'Asia/Karachi', labelKey: 'timeZone.Asia/Karachi' },
  { offset: '(UTC+05:30)', iana: 'Asia/Kolkata', labelKey: 'timeZone.Asia/Kolkata' },
  { offset: '(UTC+05:30)', iana: 'Asia/Colombo', labelKey: 'timeZone.Asia/Colombo' },
  { offset: '(UTC+05:45)', iana: 'Asia/Kathmandu', labelKey: 'timeZone.Asia/Kathmandu' },
  { offset: '(UTC+06:00)', iana: 'Asia/Bishkek', labelKey: 'timeZone.Asia/Bishkek' },
  { offset: '(UTC+06:00)', iana: 'Asia/Dhaka', labelKey: 'timeZone.Asia/Dhaka' },
  { offset: '(UTC+06:00)', iana: 'Asia/Omsk', labelKey: 'timeZone.Asia/Omsk' },
  { offset: '(UTC+06:30)', iana: 'Asia/Yangon', labelKey: 'timeZone.Asia/Yangon' },
  { offset: '(UTC+07:00)', iana: 'Asia/Barnaul', labelKey: 'timeZone.Asia/Barnaul' },
  { offset: '(UTC+07:00)', iana: 'Asia/Hovd', labelKey: 'timeZone.Asia/Hovd' },
  { offset: '(UTC+07:00)', iana: 'Asia/Krasnoyarsk', labelKey: 'timeZone.Asia/Krasnoyarsk' },
  { offset: '(UTC+07:00)', iana: 'Asia/Bangkok', labelKey: 'timeZone.Asia/Bangkok' },
  { offset: '(UTC+07:00)', iana: 'Asia/Tomsk', labelKey: 'timeZone.Asia/Tomsk' },
  { offset: '(UTC+07:00)', iana: 'Asia/Novosibirsk', labelKey: 'timeZone.Asia/Novosibirsk' },
  { offset: '(UTC+08:00)', iana: 'Asia/Shanghai', labelKey: 'timeZone.Asia/Shanghai' },
  { offset: '(UTC+08:00)', iana: 'Asia/Kuala_Lumpur', labelKey: 'timeZone.Asia/Kuala_Lumpur' },
  { offset: '(UTC+08:00)', iana: 'Australia/Perth', labelKey: 'timeZone.Australia/Perth' },
  { offset: '(UTC+08:00)', iana: 'Asia/Taipei', labelKey: 'timeZone.Asia/Taipei' },
  { offset: '(UTC+08:00)', iana: 'Asia/Ulaanbaatar', labelKey: 'timeZone.Asia/Ulaanbaatar' },
  { offset: '(UTC+08:00)', iana: 'Asia/Irkutsk', labelKey: 'timeZone.Asia/Irkutsk' },
  { offset: '(UTC+08:45)', iana: 'Australia/Eucla', labelKey: 'timeZone.Australia/Eucla' },
  { offset: '(UTC+09:00)', iana: 'Asia/Chita', labelKey: 'timeZone.Asia/Chita' },
  { offset: '(UTC+09:00)', iana: 'Asia/Tokyo', labelKey: 'timeZone.Asia/Tokyo' },
  { offset: '(UTC+09:00)', iana: 'Asia/Pyongyang', labelKey: 'timeZone.Asia/Pyongyang' },
  { offset: '(UTC+09:00)', iana: 'Asia/Seoul', labelKey: 'timeZone.Asia/Seoul' },
  { offset: '(UTC+09:00)', iana: 'Asia/Yakutsk', labelKey: 'timeZone.Asia/Yakutsk' },
  { offset: '(UTC+09:30)', iana: 'Australia/Adelaide', labelKey: 'timeZone.Australia/Adelaide' },
  { offset: '(UTC+09:30)', iana: 'Australia/Darwin', labelKey: 'timeZone.Australia/Darwin' },
  { offset: '(UTC+10:00)', iana: 'Australia/Brisbane', labelKey: 'timeZone.Australia/Brisbane' },
  { offset: '(UTC+10:00)', iana: 'Asia/Vladivostok', labelKey: 'timeZone.Asia/Vladivostok' },
  { offset: '(UTC+10:00)', iana: 'Pacific/Guam', labelKey: 'timeZone.Pacific/Guam' },
  { offset: '(UTC+10:00)', iana: 'Australia/Hobart', labelKey: 'timeZone.Australia/Hobart' },
  { offset: '(UTC+10:00)', iana: 'Australia/Sydney', labelKey: 'timeZone.Australia/Sydney' },
  { offset: '(UTC+10:30)', iana: 'Australia/Lord_Howe', labelKey: 'timeZone.Australia/Lord_Howe' },
  { offset: '(UTC+11:00)', iana: 'Pacific/Bougainville', labelKey: 'timeZone.Pacific/Bougainville' },
  { offset: '(UTC+11:00)', iana: 'Asia/Magadan', labelKey: 'timeZone.Asia/Magadan' },
  { offset: '(UTC+11:00)', iana: 'Pacific/Norfolk', labelKey: 'timeZone.Pacific/Norfolk' },
  { offset: '(UTC+11:00)', iana: 'Asia/Srednekolymsk', labelKey: 'timeZone.Asia/Srednekolymsk' },
  { offset: '(UTC+11:00)', iana: 'Asia/Sakhalin', labelKey: 'timeZone.Asia/Sakhalin' },
  { offset: '(UTC+11:00)', iana: 'Pacific/Guadalcanal', labelKey: 'timeZone.Pacific/Guadalcanal' },
  { offset: '(UTC+12:00)', iana: 'Asia/Kamchatka', labelKey: 'timeZone.Asia/Kamchatka' },
  { offset: '(UTC+12:00)', iana: 'Pacific/Auckland', labelKey: 'timeZone.Pacific/Auckland' },
  { offset: '(UTC+12:00)', iana: 'Pacific/Fiji', labelKey: 'timeZone.Pacific/Fiji' },
  { offset: '(UTC+12:00)', iana: 'Etc/GMT-12', labelKey: 'timeZone.Etc/GMT-12' },
  { offset: '(UTC+12:45)', iana: 'Pacific/Chatham', labelKey: 'timeZone.Pacific/Chatham' },
  { offset: '(UTC+13:00)', iana: 'Pacific/Tongatapu', labelKey: 'timeZone.Pacific/Tongatapu' },
  { offset: '(UTC+13:00)', iana: 'Pacific/Apia', labelKey: 'timeZone.Pacific/Apia' },
  { offset: '(UTC+13:00)', iana: 'Etc/GMT-13', labelKey: 'timeZone.Etc/GMT-13' },
  { offset: '(UTC+14:00)', iana: 'Indian/Christmas', labelKey: 'timeZone.Indian/Christmas' },
]

/**
 * 基础时区列表。
 *
 * - `id`：IANA 时区 ID。用于 Linux / Luxon 等环境。
 * - `winId`：Windows 时区 ID。用于 Windows 系统及抓取自 Windows 注册表的场景。
 * - `offset` / `zone_name`：用于在下拉框内显示 label，保持原有风格不变。
 */
export const baseZone = ZONES.map(z => ({
  offset: z.offset,
  zone_name: $t(z.labelKey),
  id: z.iana,
  winId: z.winId || winIdFromIana[z.iana] || z.iana,
}))
