/**
 * Windows 时区 ID 与 IANA 时区 ID 的双向映射
 *
 * 参考 Unicode CLDR 数据：
 *   http://cldr.unicode.org/development/development-process/design-proposals/extended-windows-olson-zid-mapping
 *
 * 使用方式：
 *   - ianaFromWinId["China Standard Time"]  // => "Asia/Shanghai"
 *   - winIdFromIana["Asia/Shanghai"]       // => "China Standard Time"
 */

// Windows 时区 ID -> IANA 时区 ID
export const ianaFromWinId: Record<string, string> = {
  'Dateline Standard Time': 'Etc/GMT+12',
  'UTC-11': 'Etc/GMT+11',
  'Aleutian Standard Time': 'America/Adak',
  'Hawaiian Standard Time': 'Pacific/Honolulu',
  'Marquesas Standard Time': 'Pacific/Marquesas',
  'Alaskan Standard Time': 'America/Anchorage',
  'UTC-09': 'Etc/GMT+9',
  'Pacific Standard Time (Mexico)': 'America/Tijuana',
  'Pacific Standard Time': 'America/Los_Angeles',
  'UTC-08': 'Etc/GMT+8',
  'Mountain Standard Time (Mexico)': 'America/Mazatlan',
  'Mountain Standard Time': 'America/Denver',
  'US Mountain Standard Time': 'America/Phoenix',
  'Yukon Standard Time': 'America/Whitehorse',
  'Pacific SA Standard Time': 'Pacific/Easter',
  'Central America Standard Time': 'America/Guatemala',
  'Central Standard Time (Mexico)': 'America/Mexico_City',
  'Canada Central Standard Time': 'America/Regina',
  'Central Standard Time': 'America/Chicago',
  'SA Pacific Standard Time': 'America/Bogota',
  'Eastern Standard Time (Mexico)': 'America/Cancun',
  'Eastern Standard Time': 'America/New_York',
  'Cuba Standard Time': 'America/Havana',
  'Haiti Standard Time': 'America/Port-au-Prince',
  'Turks And Caicos Standard Time': 'America/Grand_Turk',
  'US Eastern Standard Time': 'America/Indiana/Indianapolis',
  'Venezuela Standard Time': 'America/Caracas',
  'Paraguay Standard Time': 'America/Asuncion',
  'Atlantic Standard Time': 'America/Halifax',
  'Central Brazilian Standard Time': 'America/Cuiaba',
  'SA Western Standard Time': 'America/Port_of_Spain',
  'Pacific SA Standard Time_Santiago': 'America/Santiago',
  'Newfoundland Standard Time': 'America/St_Johns',
  'Tocantins Standard Time': 'America/Araguaina',
  'E. South America Standard Time': 'America/Sao_Paulo',
  'Argentina Standard Time': 'America/Argentina/Buenos_Aires',
  'SA Eastern Standard Time': 'America/Cayenne',
  'Montevideo Standard Time': 'America/Montevideo',
  'Magallanes Standard Time': 'America/Punta_Arenas',
  'Bahia Standard Time': 'America/El_Salvador',
  'Saint Pierre Standard Time': 'America/Miquelon',
  'Greenland Standard Time': 'America/Nuuk',
  'UTC-02': 'Etc/GMT+2',
  'Mid-Atlantic Standard Time': 'Etc/GMT+2',
  'Azores Standard Time': 'Atlantic/Azores',
  'Cape Verde Standard Time': 'Atlantic/Cape_Verde',
  'UTC': 'Etc/GMT',
  'GMT Standard Time': 'Europe/London',
  'Greenwich Standard Time': 'Africa/Monrovia',
  'Sao Tome Standard Time': 'Africa/Sao_Tome',
  'Morocco Standard Time': 'Africa/Casablanca',
  'W. Europe Standard Time': 'Europe/Berlin',
  'Central Europe Standard Time': 'Europe/Belgrade',
  'Romance Standard Time': 'Europe/Paris',
  'Central European Standard Time': 'Europe/Sarajevo',
  'W. Central Africa Standard Time': 'Africa/Lagos',
  'Jordan Standard Time': 'Asia/Amman',
  'Turkey Standard Time': 'Europe/Istanbul',
  'Libya Standard Time': 'Africa/Tripoli',
  'Namibia Standard Time': 'Africa/Windhoek',
  'South Africa Standard Time': 'Africa/Johannesburg',
  'E. Europe Standard Time': 'Europe/Helsinki',
  'Moldova Standard Time': 'Europe/Chisinau',
  'Kaliningrad Standard Time': 'Europe/Kaliningrad',
  'Syria Standard Time': 'Asia/Damascus',
  'Egypt Standard Time': 'Africa/Cairo',
  'Gaza Standard Time': 'Asia/Gaza',
  'Sudan Standard Time': 'Africa/Khartoum',
  'South Sudan Standard Time': 'Africa/Juba',
  'GTB Standard Time': 'Europe/Athens',
  'Israel Standard Time': 'Asia/Jerusalem',
  'Arabic Standard Time': 'Asia/Baghdad',
  'Belarus Standard Time': 'Europe/Minsk',
  'Russian Standard Time': 'Europe/Moscow',
  'E. Africa Standard Time': 'Africa/Nairobi',
  'Arab Standard Time': 'Asia/Kuwait',
  'Volgograd Standard Time': 'Europe/Volgograd',
  'Iran Standard Time': 'Asia/Tehran',
  'Arabian Standard Time': 'Asia/Dubai',
  'Astrakhan Standard Time': 'Europe/Astrakhan',
  'Armenian Standard Time': 'Asia/Yerevan',
  'Azerbaijan Standard Time': 'Asia/Baku',
  'Georgian Standard Time': 'Asia/Tbilisi',
  'Mauritius Standard Time': 'Indian/Mauritius',
  'Saratov Standard Time': 'Europe/Saratov',
  'Samara Standard Time': 'Europe/Ulyanovsk',
  'Afghanistan Standard Time': 'Asia/Kabul',
  'West Asia Standard Time': 'Asia/Ashgabat',
  'Bangladesh Standard Time': 'Asia/Dhaka',
  'Ekaterinburg Standard Time': 'Asia/Yekaterinburg',
  'Pakistan Standard Time': 'Asia/Karachi',
  'India Standard Time': 'Asia/Kolkata',
  'Sri Lanka Standard Time': 'Asia/Colombo',
  'Nepal Standard Time': 'Asia/Kathmandu',
  'Central Asia Standard Time': 'Asia/Bishkek',
  'N. Central Asia Standard Time': 'Asia/Omsk',
  'Myanmar Standard Time': 'Asia/Yangon',
  'SE Asia Standard Time': 'Asia/Bangkok',
  'Altai Standard Time': 'Asia/Barnaul',
  'W. Mongolia Standard Time': 'Asia/Hovd',
  'North Asia Standard Time': 'Asia/Krasnoyarsk',
  'Tomsk Standard Time': 'Asia/Tomsk',
  'N. Asia Standard Time': 'Asia/Novosibirsk',
  'China Standard Time': 'Asia/Shanghai',
  'Singapore Standard Time': 'Asia/Kuala_Lumpur',
  'W. Australia Standard Time': 'Australia/Perth',
  'Taipei Standard Time': 'Asia/Taipei',
  'Ulaanbaatar Standard Time': 'Asia/Ulaanbaatar',
  'North Asia East Standard Time': 'Asia/Irkutsk',
  'Aus Central W. Standard Time': 'Australia/Eucla',
  'Transbaikal Standard Time': 'Asia/Chita',
  'Tokyo Standard Time': 'Asia/Tokyo',
  'North Korea Standard Time': 'Asia/Pyongyang',
  'Korea Standard Time': 'Asia/Seoul',
  'Yakutsk Standard Time': 'Asia/Yakutsk',
  'Cen. Australia Standard Time': 'Australia/Adelaide',
  'AUS Central Standard Time': 'Australia/Darwin',
  'E. Australia Standard Time': 'Australia/Brisbane',
  'Vladivostok Standard Time': 'Asia/Vladivostok',
  'West Pacific Standard Time': 'Pacific/Guam',
  'Tasmania Standard Time': 'Australia/Hobart',
  'AUS Eastern Standard Time': 'Australia/Sydney',
  'Lord Howe Standard Time': 'Australia/Lord_Howe',
  'Bougainville Standard Time': 'Pacific/Bougainville',
  'Magadan Standard Time': 'Asia/Magadan',
  'Norfolk Standard Time': 'Pacific/Norfolk',
  'Sakhalin Standard Time': 'Asia/Sakhalin',
  'Central Pacific Standard Time': 'Pacific/Guadalcanal',
  'Srednekolymsk Time': 'Asia/Srednekolymsk',
  'Kamchatka Standard Time': 'Asia/Kamchatka',
  'New Zealand Standard Time': 'Pacific/Auckland',
  'UTC+12': 'Etc/GMT-12',
  'Fiji Standard Time': 'Pacific/Fiji',
  'Chatham Islands Standard Time': 'Pacific/Chatham',
  'Tonga Standard Time': 'Pacific/Tongatapu',
  'Samoa Standard Time': 'Pacific/Apia',
  'UTC+13': 'Etc/GMT-13',
  'Line Islands Standard Time': 'Indian/Christmas',
}

// 反向映射：IANA -> Windows
export const winIdFromIana: Record<string, string> = /*#__PURE__*/ (() => {
  const map: Record<string, string> = {}
  for (const [win, iana] of Object.entries(ianaFromWinId)) {
    if (!map[iana]) map[iana] = win
  }
  return map
})()
